name: Java CI with Maven and Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t test-framework .

      - name: Run tests in Docker
        run: docker run test-framework mvn test -Denv=${{ env.TEST_ENV }}
        env:
          TEST_ENV: staging